server:
  port: 8888

spring:
  application:
    name: demoElasticBeanTalk
  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    url: ${{ secrets.DATABASE_URL }}
    username: ${{ secrets.DATABASE_URSERNAME }}
    password: ${{ secrets.DATABASE_PASSWORD }}

  jpa:
    generate-ddl: false
    show-sql: true
    database: mysql
    properties:
      hibernate:
        format_sql: true